### ISSUE TITLE
Internal Server Error: Class 'League\OAuth2\Client\Provider\Linkedin' not found

### ISSUE THREAD

**Issue by mikestecker** [dukt/social-linkedin#3]
When I try to use LinkedIn with [Social Poster](https://github.com/engram-design/SocialPoster), I get the following error:

`Internal Server Error
Class 'League\OAuth2\Client\Provider\Linkedin' not found`

I'm using the latest version (`2.0.0`) and also the latest version of [OAuth](https://dukt.net/craft/oauth) (`2.0.0`) as of this writing.

**Comment by KingDaddy** [comment]
I'm getting the some @mikestecker did you ever get a fix for this?

**Comment by away86** [comment]
@mikestecker @KingDaddy make second 'i' of 'Linkedin' uppercase: 'League\OAuth2\Client\Provider\Linkedin' -> 'League\OAuth2\Client\Provider\LinkedIn'
