### ISSUE TITLE
Call to a member function getIconUrl() on null

### ISSUE THREAD

**Issue by bymayo** [dukt/social-linkedin#5]
Installed this with the latest oAuth and Social Login for Craft 2.x.

I get the error after installing the plugin and then going to the settings of Social Login to enable it.

`Call to a member function getIconUrl() on null`

**Comment by benjamindavid** [comment]
You're getting the error because you must be running OAuth 2.0 instead of 2.1. My bad though, OAuth 2.1.1 was already out but dukt.net didn't properly reflect the update, sorry about that!

**Comment by bymayo** [comment]
Perfect - thanks!
