### ISSUE TITLE
error when upgrading to 2.0.0-beta.10

### ISSUE THREAD

**Issue by bovasso** [dukt/social-linkedin#7]
After updating to 2.0.0.-beta.10, we are receiving an error on login pages:

```Access level to dukt\social\linkedin\loginproviders\Linkedin::getOauthProvider() must be public (as in class dukt\social\base\LoginProviderInterface)```

**Comment by AndrewMac** [comment]
I get exactly the same fatal error after installing Social LinkedIn, but it hits as soon as I try to open the main settings page for Social. So I can't use Social at all, and I then have to uninstall LinkedIn to get it working again. 

Social - version 2.0.0-beta.14
Social LinkedIn - version 3.0.2

I'd really like to offer LinkedIn registration, but I can't actually go ahead and purchase Social until this is fixed, sadly.

So I really hope you'll be able to look at this sometime soon ... please? ;-)

**Comment by benjamindavid** [comment]
Sorry about that guys. Social LinkedIn 3.0.3 has just been released and should fix this issue:
https://github.com/dukt/social-linkedin/blob/v3/CHANGELOG.md#303---2018-09-20
